# Default of Credit Card Clients Dataset

In [8]:
# Load libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn import metrics

In [2]:
data = pd.read_csv("D:\\Datasets\\default of credit card clients.csv",delimiter=',')
data.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1      20000    2          2         1   24      2      2     -1     -1   
1   2     120000    2          2         2   26     -1      2      0      0   
2   3      90000    2          2         2   34      0      0      0      0   
3   4      50000    2          2         1   37      0      0      0      0   
4   5      50000    1          2         1   57     -1      0     -1      0   

              ...              BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  \
0             ...                      0          0          0         0   
1             ...                   3272       3455       3261         0   
2             ...                  14331      14948      15549      1518   
3             ...                  28314      28959      29547      2000   
4             ...                  20940      19146      19131      2000   

   PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0       689         0         0         0         0   
1      1000      1000      1000         0      2000   
2      1500      1000      1000      1000      5000   
3      2019      1200      1100      1069      1000   
4     36681     10000      9000       689       679   

   default payment next month  
0                           1  
1                           1  
2                           0  
3                           0  
4                           0  

[5 rows x 25 columns]

In [4]:
# Spliting Target Variable
predictor= data.iloc[:, data.columns != 'default payment next month']
target= data.iloc[:, data.columns == 'default payment next month']

In [5]:
# Standarize features
scaler = StandardScaler()
predictor = scaler.fit_transform(predictor)

In [6]:
#Let us now split the dataset into train & test
from sklearn.cross_validation import train_test_split
x_train,x_test, y_train, y_test = train_test_split(predictor, target, test_size = 0.30, random_state=0)
print("x_train ",x_train.shape)
print("x_test ",x_test.shape)
print("y_train ",y_train.shape)
print("y_test ",y_test.shape)

x_train  (21000, 24)
x_test  (9000, 24)
y_train  (21000, 1)
y_test  (9000, 1)


C:\Users\computer\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [9]:
# Create support vector classifier object
svc = SVC(kernel='linear', random_state=0)

# Train classifier
model = svc.fit(x_train,y_train)

C:\Users\computer\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [10]:
# View support vectors
model.support_vectors_

array([[-0.57013339,  0.25061122, -1.23432296, ..., -0.24218699,
        -0.2283922 , -0.18087821],
       [-0.99483225, -1.13672015,  0.81016074, ...,  0.01110202,
        -0.26812239, -0.24978682],
       [ 0.1806529 ,  1.17549879, -1.23432296, ..., -0.29082767,
         2.4780394 ,  5.33192292],
       ..., 
       [-0.95326303, -1.21379411, -1.23432296, ..., -0.26976281,
        -0.30104544, -0.2652561 ],
       [ 0.66481884, -1.13672015, -1.23432296, ..., -0.13571369,
        -0.31413612, -0.2596309 ],
       [ 0.53676255,  0.32768518,  0.81016074, ...,  0.02731558,
         0.03931211,  0.0092533 ]])

In [11]:
# View indices of support vectors
model.support_

array([    1,     3,     5, ..., 20985, 20991, 20996])

In [12]:
# View number of support vectors for each class
model.n_support_

array([5740, 4643])

In [19]:
# Create support vector classifier object
svc = SVC(kernel='poly', random_state=0)

# Train classifier
model = svc.fit(x_train,y_train)

C:\Users\computer\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [20]:
# View support vectors
model.support_vectors_

array([[ 0.10686753, -1.05964618,  0.81016074, ..., -0.30806256,
        -0.31413612, -0.29338206],
       [-0.57013339,  0.25061122, -1.23432296, ..., -0.24218699,
        -0.2283922 , -0.18087821],
       [-1.44020025,  1.71501654, -1.23432296, ..., -0.30806256,
         0.02046153, -0.29338206],
       ..., 
       [ 0.41644275, -0.90549825,  0.81016074, ..., -0.25795372,
        -0.27113325, -0.25288067],
       [-0.95326303, -1.21379411, -1.23432296, ..., -0.26976281,
        -0.30104544, -0.2652561 ],
       [ 0.53676255,  0.32768518,  0.81016074, ...,  0.02731558,
         0.03931211,  0.0092533 ]])

In [21]:
# View indices of support vectors
model.support_

array([    0,     1,     9, ..., 20979, 20985, 20996])

In [22]:
# View number of support vectors for each class
model.n_support_

array([4768, 4358])

In [23]:
# Create support vector classifier object
svc = SVC(kernel='rbf', random_state=0)

# Train classifier
model = svc.fit(x_train,y_train)

C:\Users\computer\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [24]:
# View support vectors
model.support_vectors_

array([[-0.57013339,  0.25061122, -1.23432296, ..., -0.24218699,
        -0.2283922 , -0.18087821],
       [ 0.50535469,  2.56283015,  0.81016074, ...,  1.66079992,
         0.25498098, -0.09470026],
       [-0.30189646, -0.90549825,  0.81016074, ..., -0.24422965,
        -0.22315593, -0.22869234],
       ..., 
       [-0.95326303, -1.21379411, -1.23432296, ..., -0.26976281,
        -0.30104544, -0.2652561 ],
       [ 0.66481884, -1.13672015, -1.23432296, ..., -0.13571369,
        -0.31413612, -0.2596309 ],
       [ 0.53676255,  0.32768518,  0.81016074, ...,  0.02731558,
         0.03931211,  0.0092533 ]])

In [25]:
# View indices of support vectors
model.support_

array([    1,     2,     7, ..., 20985, 20991, 20996])

In [26]:
# View number of support vectors for each class
model.n_support_

array([5319, 4099])